### ISSUE TITLE
Remove camel-json-validator

### ISSUE THREAD

**Issue by MuglaAllan** [DVSJersey/vrs-api#2]
<dependency>
	    <groupId>com.github.everit-org.json-schema</groupId>
	    <artifactId>org.everit.json.schema</artifactId>
	    <version>1.6.0</version>
</dependency>

<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-json-validator</artifactId>
    <version>x.y.z</version>
    
</dependency>

**Comment by tdcox** [comment]
Now safe to use this dependency again.
